import httpClient from './http/HttpClient.js';

/**
 * AuthService - Manages user authentication and company registration.
 *
 * Single Responsibility: All operations related to user identity.
 *  - Login (token acquisition), client and company
 *  - Company registration (the chat flow still registers companies —
 *    client registration now happens on the web, see RegistrationHandler)
 */
class AuthService {

    /**
     * Authenticate a WhatsApp user against the backend.
     * Stores the token in HttpClient on success.
     *
     * @param {string} whatsappId - Normalized WhatsApp ID (phone number or JID prefix)
     * @returns {Promise<Object|null>} User object or null if not found
     */
    async authenticate(whatsappId) {
        return this._doLogin(whatsappId);
    }

    /**
     * @private
     */
    async _doLogin(whatsappId) {
        const result = await httpClient.request('POST', '/afrik/login', { whatsapp: whatsappId });

        if (result.success && result.data?.token) {
            httpClient.setToken(whatsappId, result.data.token);
            console.log(`[AuthService] Authenticated: ${result.data.user?.nom} ${result.data.user?.prenom}`);
            return result.data.user;
        }

        if (result.status === 404) {
            console.log(`[AuthService] User not found: ${whatsappId}`);
            return null;
        }

        const msg = result.error?.message || result.error?.error || 'Unknown error';
        throw new Error(`Authentication failed: ${msg}`);
    }

    /**
     * Authenticate a WhatsApp number as a COMPANY against the backend.
     * Mirrors authenticate()/_doLogin() but against the Company table.
     *
     * @param {string} whatsappId
     * @returns {Promise<Object|null>} Company object or null if not found
     */
    async authenticateCompany(whatsappId) {
        const result = await httpClient.request('POST', '/afrik/company-login', { whatsapp: whatsappId });

        if (result.success && result.data?.token) {
            httpClient.setToken(whatsappId, result.data.token);
            console.log(`[AuthService] Company authenticated: ${result.data.company?.name}`);
            return result.data.company;
        }

        if (result.status === 404) {
            return null;
        }

        const msg = result.error?.message || result.error?.error || 'Unknown error';
        throw new Error(`Company authentication failed: ${msg}`);
    }

    /**
     * Register a new company and store its token.
     *
     * @param {Object} companyData - { company_name, whatsapp, email, ifu, num_mtn, num_moov, num_celtiis, terms_accepted }
     * @returns {Promise<{company: Object, generated_password: string}>}
     */
    async registerCompany(companyData) {
        const result = await httpClient.request('POST', '/afrik/register-company', companyData);

        if (result.success && result.data?.token) {
            httpClient.setToken(companyData.whatsapp, result.data.token);
            console.log(`[AuthService] Company registered: ${result.data.company?.name}`);
            return result.data;
        }

        const fieldErrors = Object.values(result.error?.errors || {}).flat();
        const msg = result.error?.message || fieldErrors[0] || 'Erreur inconnue';
        throw new Error(msg);
    }

    /**
     * Clear the stored token for a user (logout).
     * @param {string} whatsappId
     */
    logout(whatsappId) {
        httpClient.clearToken(whatsappId);
    }

    /**
     * Confirm a passwordless WhatsApp login/link token, generated by the site
     * (sign-in page or "link my WhatsApp" settings action). This is the bot's
     * only role in that flow: prove which WhatsApp identity just replied.
     * The backend returns a ready-to-send confirmation message either way
     * (success or failure) — never throws, so the caller can just relay it.
     *
     * @param {string} token
     * @param {string} whatsappId - Normalized WhatsApp ID (this session's identity)
     * @param {boolean} isLid
     * @returns {Promise<string>} Message to send back to the user
     */
    async confirmWhatsAppLogin(token, whatsappId, isLid) {
        const result = await httpClient.request('POST', '/afrik/whatsapp-login-confirm', {
            token,
            whatsapp: whatsappId,
            is_lid: isLid,
        });

        if (result.data?.message) return result.data.message;
        return result.error?.message || 'Une erreur est survenue. Réessayez depuis le site.';
    }
}

export default new AuthService();
